# This is a basic workflow to help you get started with Actions

name: Daily track + simapp update

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Setup Python
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Update tracks
        run: |
          pip install "git+https://github.com/aws-deepracer-community/deepracer-race-stats.git@v0.2.4" 
          drs track-update -o raw_data

      - name: Commit tracks
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./raw_data
          git commit -m "Track update" || echo "No changes to commit"

      - name: Update simapp
        run: |
          pip install "git+https://github.com/aws-deepracer-community/deepracer-race-stats.git@v0.2.4" 
          drs simapp-update -o raw_data

      - name: Commit simapp
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./raw_data
          git commit -m "Simulation application update" || echo "No changes to commit"

      - name: Update documentation
        run: |
          pip install -r requirements.txt
          python ./scripts/documentation.py

      - name: Commit documentation
        run: |
          git add ./raw_data
          git commit -m "Documentation update" || echo "No changes to commit"
          git push
